# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd7c205eb73e70d1779342ef9e750090b549747cb1f8336615f6eb6f0ba42ffc71c7c8a30b301b1c656d9cd3e17bfb7a1d538793fd9259d4923d49f6a0c7d567
  MAILCHIMP_API_KEY: 0d1d063ca1b3dabd6ff5616fea0570a5-us7
  MAILCHIMP_AFFILIATE_LIST: "64511c38f6"
  MAILCHIMP_WWO_LIST: "a0e2bbe30f"
  MAILCHIMP_MAIN: "a0e73ca86a"
  MANDRILL_API_KEY: YUQ9o_LKpPdItzA3HFDmGg
  MANDRILL_USERNAME: "joe@joebuhlig.com"
  BRAINTREE_MERCHANT_ID: 'fx9h2wf3jq7zcqhd'
  BRAINTREE_PUBLIC_KEY: 'jspfk24gmkqfgy4d'
  BRAINTREE_PRIVATE_KEY: '0c84da675989988f0b6e87d77b4f0d4b'
  BRAINTREE_ENV: :sandbox

test:
  secret_key_base: 9de55af72eefcc2dbb90d5fd77a1d9b97f426dfe504a5a86ce4da2cdc23d57ad6e033750be189b36a726a82e29aa10be37e10606b23f39fd72ead3e5ce28e440

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_KEY_BASE"] %>
  MAILCHIMP_API_KEY: "<%= ENV["MAILCHIMP_API_KEY"] %>"
  MAILCHIMP_AFFILIATE_LIST: "<%= ENV["MAILCHIMP_AFFILIATE_LIST"] %>"
  MAILCHIMP_WWO_LIST: "<%= ENV["MAILCHIMP_WWO_LIST"] %>"
  MAILCHIMP_MAIN: "<%= ENV["MAILCHIMP_MAIN"] %>"
  MANDRILL_API_KEY: <%= ENV["MANDRILL_API_KEY"] %>
  MANDRILL_USERNAME: "<%= ENV["MANDRILL_USERNAME"] %>"
  BRAINTREE_MERCHANT_ID: '<%= ENV["BRAINTREE_MERCHANT_ID"] %>'
  BRAINTREE_PUBLIC_KEY: '<%= ENV["BRAINTREE_PUBLIC_KEY"] %>'
  BRAINTREE_PRIVATE_KEY: '<%= ENV["BRAINTREE_PRIVATE_KEY"] %>'
  BRAINTREE_ENV: :production